### ISSUE TITLE
Sakana feature tracking

### ISSUE THREAD

**Issue by inventionpro** [inventionpro/Sakana#1]
Roadmap:
- [ ] Start
- [ ] Set up main class
- [ ] Set up Runner Class
- [ ] NSP file decoding
- [ ] NCA file decrypting
- [ ] Read content
- [ ] Start emulating (will be expanded later)
- [ ] Ship 1.0.0
